"""A light-weight python wrapper for the Datawrapper API (v3). While it is not developed by Datawrapper officially, you can use it with your API credentials from datawrapper.de"""

try:
    from importlib.metadata import PackageNotFoundError, version  # type: ignore
except ImportError:  # pragma: no cover
    from importlib_metadata import PackageNotFoundError, version  # type: ignore


try:
    __version__ = version(__name__)
except PackageNotFoundError:  # pragma: no cover
    __version__ = "unknown"

from datawrapper.chart_factory import get_chart
from datawrapper.charts import (
    Annotate,
    AreaChart,
    AreaFill,
    AreaMarker,
    AreaProperties,
    ArrowChart,
    BarChart,
    BarOverlay,
    BaseChart,
    ChoroplethMap,
    ColumnChart,
    ColumnFormat,
    ConnectorLine,
    Describe,
    GeoJSONFeature,
    GeoJSONGeometry,
    Line,
    LineChart,
    LineMarker,
    LineProperties,
    LineSymbol,
    LineValueLabel,
    LocatorMap,
    MapKey,
    MapView,
    MapVisibility,
    MarkerIcon,
    MarkerText,
    MarkerTooltip,
    MarkerVisibility,
    MiniMap,
    MultipleColumnChart,
    MultipleColumnRangeAnnotation,
    MultipleColumnTextAnnotation,
    MultipleColumnXLineAnnotation,
    MultipleColumnXRangeAnnotation,
    MultipleColumnYLineAnnotation,
    MultipleColumnYRangeAnnotation,
    PointMarker,
    RangeAnnotation,
    ScatterPlot,
    StackedBarChart,
    Table,
    TextAnnotation,
    Tooltip,
    Transform,
    XLineAnnotation,
    XRangeAnnotation,
    YLineAnnotation,
    YRangeAnnotation,
    Table
)
from datawrapper.charts.enums import (
    ArrowHead,
    BasemapProjection,
    ColorMode,
    ColorScale,
    ConnectorLineType,
    DateFormat,
    GridDisplay,
    GridLabelAlign,
    GridLabelPosition,
    LineDash,
    LineInterpolation,
    LineWidth,
    MapStyle,
    NumberDivisor,
    NumberFormat,
    PlotHeightMode,
    RegressionMethod,
    ReplaceFlagsType,
    ScatterAxisPosition,
    ScatterGridLines,
    ScatterShape,
    ScatterSize,
    StrokeType,
    StrokeWidth,
    SymbolDisplay,
    SymbolShape,
    SymbolStyle,
    TextAlign,
    ValueLabelAlignment,
    ValueLabelDisplay,
    ValueLabelMode,
    ValueLabelPlacement,
)
from datawrapper.charts.models import (
    CustomRangeMixin,
    CustomTicksMixin,
    GridDisplayMixin,
    GridFormatMixin,
)
from datawrapper.exceptions import (
    FailedRequestError,
    InvalidRequestError,
    RateLimitError,
)
from datawrapper.flags import get_country_flag

from .__main__ import Datawrapper

__all__ = [
    "Datawrapper",
    "get_chart",
    "BaseChart",
    "Annotate",
    "ColumnFormat",
    "Transform",
    "Describe",
    "BarChart",
    "BarOverlay",
    "ChoroplethMap",
    "ColumnChart",
    "LineChart",
    "Line",
    "LineSymbol",
    "LineValueLabel",
    "AreaFill",
    "AreaChart",
    "ArrowChart",
    "LocatorMap",
    "MapKey",
    "MapView",
    "MapVisibility",
    "MiniMap",
    "PointMarker",
    "AreaMarker",
    "LineMarker",
    "MarkerIcon",
    "MarkerText",
    "MarkerTooltip",
    "MarkerVisibility",
    "AreaProperties",
    "LineProperties",
    "GeoJSONFeature",
    "GeoJSONGeometry",
    "MultipleColumnChart",
    "MultipleColumnTextAnnotation",
    "MultipleColumnRangeAnnotation",
    "MultipleColumnXLineAnnotation",
    "MultipleColumnXRangeAnnotation",
    "MultipleColumnYLineAnnotation",
    "MultipleColumnYRangeAnnotation",
    "ScatterPlot",
    "StackedBarChart",
    "Table",
    "TextAnnotation",
    "RangeAnnotation",
    "XRangeAnnotation",
    "YRangeAnnotation",
    "XLineAnnotation",
    "YLineAnnotation",
    "ConnectorLine",
    "Tooltip",
    "ArrowHead",
    "BasemapProjection",
    "ColorMode",
    "ColorScale",
    "ConnectorLineType",
    "DateFormat",
    "GridDisplay",
    "GridLabelAlign",
    "GridLabelPosition",
    "LineDash",
    "LineInterpolation",
    "LineWidth",
    "MapStyle",
    "NumberDivisor",
    "NumberFormat",
    "PlotHeightMode",
    "RegressionMethod",
    "ReplaceFlagsType",
    "ScatterAxisPosition",
    "ScatterGridLines",
    "ScatterShape",
    "ScatterSize",
    "StrokeType",
    "StrokeWidth",
    "SymbolDisplay",
    "SymbolShape",
    "SymbolStyle",
    "TextAlign",
    "ValueLabelAlignment",
    "ValueLabelDisplay",
    "ValueLabelMode",
    "ValueLabelPlacement",
    "get_country_flag",
    "CustomRangeMixin",
    "CustomTicksMixin",
    "GridFormatMixin",
    "GridDisplayMixin",
    "FailedRequestError",
    "InvalidRequestError",
    "RateLimitError",
    "Table"
]
